# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 17:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageText',
            fields=[
                ('style', models.CharField(blank=True, default=b'', max_length=31)),
                ('anchor', models.CharField(blank=True, default=b'', max_length=127)),
                ('hide', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, default='')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
