# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('djangocms_imagetext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetext',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_imagetext_imagetext', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
    ]
