# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 17:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_text_text', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(blank=True, default=b'', max_length=31)),
                ('anchor', models.CharField(blank=True, default=b'', max_length=127)),
                ('hide', models.BooleanField(default=False)),
                ('body', ckeditor.fields.RichTextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
