# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='anchor',
            field=models.SlugField(blank=True, default=b''),
        ),
    ]
