# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20170805_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpluginmodel',
            name='field1_de',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testpluginmodel',
            name='field1_en',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
