name: Release on PYPI
on:
  push:
    branches:  [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.repository == 'bnzk/djangocms-misc'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist
        python setup.py bdist_wheel --universal
    - name: Publish
      env:
        PYPI_UPLOAD_TOKEN: ${{ secrets.PYPI_UPLOAD_TOKEN }}
      run: twine upload --user __token__ --password $PYPI_UPLOAD_TOKEN dist/*
